export const content = {
  header: {
    logo: '/logo.webp',
    navLinks: [
      { href: '#projects', text: 'Projects' },
      { href: '#skills', text: 'Skills' },
      { href: '#contact', text: 'Contact' },
    ],
    socialLinks: {
      github: 'https://github.com/rishi0810',
      linkedin: 'https://linkedin.com/in/rishiraj2003',
    },
  },
  heroSection: {
    name: 'RISHI RAJ',
    bio: "I mostly make full stack stuff. I also love learning new technologies as they come out, just to try my best to stay ahead of the curve. If you fear the change, you will be left behind.",
    cvUrl: '/Resume.pdf',
    avatar: '/pfp.webp',
  },
  projectsSection: {
    title: 'My Projects',
    subtitle: 'Every project is a unique experience. Check out some stuff I have worked on so far',
    projects: [
      {
        name: 'Bable',
        logoUrl: '/screenshots/bbl.avif',
        desktopImageUrl: '/screenshots/bbd.webp',
        mobileImageUrl: '/screenshots/bbm.webp',
        oneLiner: 'Blogging website, fully supporting markdown text formatting with images',
        githubUrl: 'https://github.com/rishi0810/Bable',
        liveUrl: 'https://bable.vercel.app/',
        techStack: ['React', 'Tailwind', 'MongoDB', 'Express'],
      },
      {
        name: 'JeeNeetards',
        logoUrl: '/screenshots/jnl.svg',
        desktopImageUrl: '/screenshots/jnd.webp',
        mobileImageUrl: '/screenshots/jnm.webp',
        oneLiner: 'AI-powered progress tracker for competetive exams',
        githubUrl: 'https://github.com/rishi0810/JeeNeeTards',
        liveUrl: 'https://jeeneetardsv1.vercel.app/',
        techStack: ['React', 'Tailwind', 'Gemini'],
      },
      {
        name: 'Musicality',
        logoUrl: '/screenshots/mcli.webp',
        desktopImageUrl: '/screenshots/mcld.webp',
        mobileImageUrl: '/screenshots/mclm.webp',
        oneLiner: 'Music app based on JioSaavn backend',
        githubUrl: 'https://github.com/rishi0810/Musicality',
        liveUrl: 'https://musicalty-mapp.vercel.app/',
        techStack: ['React', 'Tailwind', 'HTML'],
      },
      {
        name: 'LeafLens-AI',
        logoUrl: '/screenshots/lll.svg',
        desktopImageUrl: '/screenshots/lld.webp',
        mobileImageUrl: '/screenshots/llm.webp',
        oneLiner: 'AI-powered disease detector in plants',
        githubUrl: 'https://github.com/rishi0810/LeafLens-AI',
        liveUrl: 'https://leaf-lens-ai.vercel.app/',
        techStack: ['Express', 'Gemini', 'React'],
      },
    ],
  },
  skillsSection: {
    title: 'Technical Skills',
    skills: [
        { name: 'JavaScript', imageUrl: 'https://img.shields.io/badge/JavaScript-323330?style=for-the-badge&logo=javascript&logoColor=F7DF1E' },
        { name: 'Java', imageUrl: 'https://img.shields.io/badge/Java-ED8B00?style=for-the-badge&logo=openjdk&logoColor=white' },
        { name: 'HTML', imageUrl: 'https://img.shields.io/badge/HTML5-E34F26?style=for-the-badge&logo=html5&logoColor=white' },
        { name: 'CSS', imageUrl: 'https://img.shields.io/badge/CSS3-1572B6?style=for-the-badge&logo=css3&logoColor=white' },
        { name: 'React', imageUrl: 'https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB' },
        { name: 'Next.js', imageUrl: 'https://img.shields.io/badge/Next.js-000000?style=for-the-badge&logo=next.js&logoColor=white' },
        { name: 'Node.js', imageUrl: 'https://img.shields.io/badge/Node.js-339933?style=for-the-badge&logo=nodedotjs&logoColor=white' },
        { name: 'Express', imageUrl: 'https://img.shields.io/badge/Express.js-000000?style=for-the-badge&logo=express&logoColor=white' },
        { name: 'Tailwind', imageUrl: 'https://img.shields.io/badge/Tailwind_CSS-38B2AC?style=for-the-badge&logo=tailwind-css&logoColor=white' },
        { name: 'MongoDB', imageUrl: 'https://img.shields.io/badge/MongoDB-4EA94B?style=for-the-badge&logo=mongodb&logoColor=white' },
        { name: 'Springboot', imageUrl: 'https://img.shields.io/badge/Spring_Boot-6DB33F?style=for-the-badge&logo=spring-boot&logoColor=white' },
        { name: 'Git', imageUrl: 'https://img.shields.io/badge/Git-F05032?style=for-the-badge&logo=git&logoColor=white' },
        { name: 'GitHub', imageUrl: 'https://img.shields.io/badge/GitHub-181717?style=for-the-badge&logo=github&logoColor=white' },
        { name: 'Gemini', imageUrl: 'https://img.shields.io/badge/Gemini-181717?style=for-the-badge&logo=gemini&logoColor=white' },
    ]
  },
  experienceSection: {
    title: 'Work Experience & Education',
    experiences: [
      {
        id: 1,
        date: '2025 June - Present',
        title: 'Technical Product Intern',
        company: 'Times of India',
        description: 'In charge of designing end-to-end Proof of Concepts, including all stack apps.',
        iconUrl: '/toi.webp',
        responsibilities: [
          'Designing and creating functional POCS',
          'Collaborating with cross-functional teams to streamline new features and TOF improvements',
          'Creating Games for TOI app',
        ],
      },
       {
        id: 2,
        date: '2023 Oct - 2025 Jan',
        title: 'Content Team Lead',
        company: "Institution's Innovation Council",
        description: 'In charge of creating ledes, reports, analysis and handling content',
        iconUrl: '/iic.webp',
        responsibilities: [
          'Generated reports for Ministry of Education AICTE panel',
          'In charge of managing content worflow for social media posts',
          'Handling Newsletter creation and Design',
        ],
      },
      {
        id: 3,
        date: '2022 - Present',
        title: 'Undergrad - Bachelor in Technology',
        company: 'Guru Gobind Singh Indraprastha University',
        description: 'Education in B.Tech primarily focused on technology and theoretical insight into the field',
        iconUrl: '/uni.svg',
        iconUrlDark: '/uni.svg',
        responsibilities: [],
      },
    ],
  },
  contactSection: {
    title: 'Get in Touch',
    subtitle: "Have a project in mind, or just want to say hi? I'd love to hear from you.",
    email: 'mailto:rishi.1003raj@gmail.com',
    phone: '+91-9911449830'
  },
  footer: {
    text: '© 2025 Rishi Raj. All rights reserved.',
  },
};
